---
- name: Configure NSGs for Azure VM
  hosts: localhost
  tasks:
    - name: Create a Network Security Group
      azure_rm_securitygroup:
        resource_group: "demo-resource-group"
        name: "my-nsg"
        rules:
          - name: "SSH"
            access: "Allow"
            direction: "Inbound"
            protocol: "Tcp"
            priority: 1000
            source_address_prefix: "*"
            source_port_range: "*"
            destination_address_prefix: "*"
            destination_port_range: "22"
          - name: "HTTP"
            access: "Allow"
            direction: "Inbound"
            protocol: "Tcp"
            priority: 1001
            source_address_prefix: "*"
            source_port_range: "*"
            destination_address_prefix: "*"
            destination_port_range: "80"
      register: nsg

    - name: Associate NSG with the VM's network interface
      azure_rm_networkinterface:
        resource_group: "demo-resource-group"
        name: "my-demo-net-nic"
        virtual_network: "my-demo-net"
        enable_ip_forwarding: false
        network_security_group: "{{ nsg.id }}"
